import type { Metadata } from 'next'
import { Nunito_Sans, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
})

const nunitoSans = Nunito_Sans({
    variable: '--font-nunito',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Real State',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" data-theme="light">
            <body className={`${poppins.variable} ${nunitoSans} antialiased`}>
                {children}
            </body>
        </html>
    )
}
